### PR TITLE
feat: allow markdown convertor to parse image dimensions

### PR DESCRIPTION
**Pull request by jeeyyy**
@jeankaplansky wanted to have this option enabled with showdown.
See more documentation here - https://github.com/showdownjs/showdown/wiki/Showdown-Options#parseimgdimensions

## Reviewer checks

**Required fields, to be filled out by PR reviewer(s)**
- [ ] Code is reviewed for security

### CODE REVIEW

**Comment by jeeyyy** [comment]
@jeankaplansky please write up an issue for this as @WilcoFiers wants one.

**Comment by jeankaplansky** [comment]
`parseImgDimensions` enables us to resize images directly in markdown without needing to use  HTML markup in our markdown files:

> parseImgDimensions: (boolean) [default false] Enable support for setting image dimensions from within markdown syntax. Examples:

> foo     simple, assumes units are in px
> bar      sets the height to "auto"
> baz  Image with width of 80% and height of 5em

source: https://github.com/showdownjs/showdown

Wilco really doesn't want to mix HTML with markdown if we can get away from it.

**Comment by jeeyyy** [comment]
@jeankaplansky - Can you add examples of where currently you are using HTML markup for images. This will help.

**Comment by WilcoFiers** [comment]
This PR needs an issue that is put into the sprint. Please follow the process.

**Comment by jeeyyy** [comment]
@jeankaplansky could you write up an issue for this please. Thanks.

**Pull request closed without merging**
